### PR TITLE
Public deploylist

### PR DESCRIPTION
**Pull request by mrship**
:repeat: Allows deploylist to monitor its own deploys
:eyes: Publicly visible at https://deploylist-public.herokuapp.com
:unlock: Various service keys used are locked for use on this OSS project
:memo: This makes it easier to start with deploylist as you can work on it locally with the deploy history of deploylist itself.

### CODE REVIEW

**Comment by andycroll** [comment]
Meta.

**Comment by matthutchinson** [comment]
Looks good to me, the only other thing i'd suggest is updating the readme, to provide instructions (or links to pages that have instructions) for how to set up the integrations (i.e. get all the things you need for your own `.env` file).

**Comment by mrship** [comment]
There are instructions for the tricky one - OAuth - hopefully the others should be simple enough to someone deploying this.

**Comment by dncrht** [comment]
Jus in case someone asks, @mrship states "the keys are limited to the scope of that project and the project itself is OSS, so it is fine"

**Pull request merged**
